export var settingVariables = {
    Static: "Click slide type to add your first slide.",
    MutlipleChoice: "Multiple Choice",
    WordCloud: "Word Cloud",
    OpenEnded: "Open Ended",
    Scales: "Scales",
    Ranking: "Ranking",
    QA: "QA",
    Heading: "Heading",
    Paragraph:"Paragraph",
    Big:"BIG",
    Bullets:"Bullets",
    Image:"Image",
    Quote:"Quote",
    Video:"Video",
    Grid:"Grid",
    Quiz:"Quiz",
    TwoChartGrid:"TwoGrid",
    FourChartGrid:"FourGrid",
    Instructions:"Instructions",
    Number:"Number",
    SelectAnswers:"Select Answer",
    LeaderBoard:"Leader Board",
    TypeAnswers:"Type Answer",
    GuessTheNumber:"Guess the Number",
    //For timer slide
    Timer:"Timer",
    Duration:"Duration",
    TimerDateTime:"TimerDateTime",
    TimerDate:"TimerDate",
    TimerTime:"TimerTime",
    // Timerslide end
    ThisorThat:"This or That",
    TruthorLie:"Truth or Lie",
    TrafficLights:"Traffic Lights",
    Document:"Document",
    SlideType: "Slide Type",
    Content: "Content",
    POPULAR:"POPULAR",
    QUIZ:"QUIZ",
    CONTENT:"CONTENT",
    ADVANCED:"ADVANCED",
    QUESTIONS:"QUESTIONS",
    // for Import options
    IMPORT: "IMPORT",
    ImportDocument: "Import Document",
    ImportPowerpoint: "PowerPoint",
    GoogleSlides: "Google Slides",
    // For powerpoint web
    EmbedLink: "Embed Link",
    SlideIndex: "Slide Index",
    // For Google slides
    slideNumber: "Slidenumber",
    slidesLink: "SlidesLink",
    Design: "Design",
    Layout: "Layout",
    Settings: "Settings",
    Presenter: "Presenter",
    YourQuestion: "Your Question",
    AboutTheSlide: "About The Slide",
    LongDescription: "Long Description",
    Option: "Option ",
    DimensionsAxis:"Dimensions Axis",
    LowValue:"Low Value",
    HighValue:"High Value",
    AxisMin:"Axis Min",
    AxisMax:"Axis Max",
    Statment: "Statement ",
    GuessTheNumberCorrectAnswers:"CorrectAnswers",
    GuessTheNumberStart:"Start",
    GuessTheNumberEnd:"End",
    GuessTheNumberScaleIncrement:"Increment",
    GuessTheNumberErrorMargin:"Error Margin",
    Item: "Item ",
    Bullet: "Bullet ",
    Arrows:"Arrows",
    DrumRoll:"Drum Roll",
    Breathe:"Breather",
    Breather:"Breathe",
    Loop:"Loop",
    SpintheWheel:"Spin the Wheel",
    Timeline:"Timeline",
    Whowillwin:"Who will win?",
    HundredPoints:"100 points",
    QuickForm:"Quick Form",
    Miro:"Miro",
    FieldOption:"Field Option",
    SubOption:"Sub Option",
    PinonImage:"Pin on Image",
    Contestant: "Contestant",
    DisplayCorrectAnswers:"Correct answer to display",
    CorrectAnswers:"Correct answer",
    NOofEntries: "No of entries",
    SecondsToAnswer: "Seconds to answer",
    FastAnswers: "Fast Answers",
    Leaderboard: "Leader Board",
    LocalAPIURL: "https://localhost:7229/api/v1/",
    LocalAudienceAPIURL: "https://localhost:7230/",
    LocalAudienceURL: "https://localhost:7230",
    LocalUIURL: "https://localhost:4200",
    AudienceApi: 'https://localhost:7230/api/v1/',
    AudienceUI:'http://localhost:4201/',
    EnvironmentlOCALMode: "LOCAL",
    EnvironmentDEVMode: "DEV",
    EnvironmentTESTMode: "TEST",
    PresenterPhase: "PresenterPhase",
    AudiencePhase: "AudiencePhase",
    AnswerMultipleTimes: "AnswerMultipleTimes",
    ThemeName : "Theme Name",
    ContentType:"CONTENT",
    ApplyThemeType:"ApplyTheme",
    EditThemeType:"EditTheme",
    DefaultThemeType:"DefaultTheme",
    LayoutDefault:"default",
    LayoutLeft:"Left",
    LayoutRight:"Right",
    LayoutInnerRight:"InnerRight",
    LayoutInnerLeft:"InnerLeft",
    LayoutBackground:"Background",
    LayoutBgRight:"Background-Right",
    LayoutBgLeft:"Background-Left",
    LayoutBgTop:"Background-Top",
    LayoutBgBottom:"Background-Bottom",
    AlignmentLeft:0,
    AlignmentRight:2,
    AlignmentCenter:1,
    // For Scales Dimensions
    Agree:'Strongly agree',
    Disagree:'Strongly disagree',
    Custom:'Custom label',
    SlideImage : "SlideImage",
    DesignImage : "DesignImage",
    ThemeImage : "ThemeImage",
    LogoImaged : "LogoImage",

    //Chart Type
    Bar:"Bar",
    Pie:"Pie",
    Donut:"Donut",
    Dot:"Dot",
    Speech:"Speech",
    Flowing:"Flowing",
    Slider:"Slider",
    Spider:"Spider",
    TwoGrid:"2 x 2 Grid",
    FourGrid:"4 x 4 Grid",
    SelectedAnswerVisual:"Select Answers",
    TypeAnswerVisual:"Type Answers",
    slidewithHeading:"Slide with heading",
    QuestionandAnswer:"Ask me anything",
    SlidewithParagraph:"Slide with paragraph",
    SlidewithBullets:"Slide with bullets",
    Titleofquickform:"Title of Quick form",
    Red:"Red",
    Yellow:"Yellow",
    Green:"Green",
     GuessTheNumbers:"Guess the Number",
    AskMeAnything :"Ask me anything",
    SlideWithHeading:"Slide with heading",
    // SlideWithParagraph:"Slide with paragraph",
    // SlideWithBullets:"Slide with Bullets",
    Quotes:"Quotes",
    Hundred:"100",
    Instruction:"Instruction",
    Breathes:"Breathe",
    // Timelines:"Timeline",
    Titleofquickforms:"Title of Quick Form",
    PinonImages:"Pin on image",
    WhatIsYourProfession:"What is your profession?",
    WhatIsYourEmailAddress:"What is your email address?",
    VideoCaption:"Video caption",
    ImageCaption:"Image caption",
    Leaderboards: "Leaderboard",


    RatioFree:'Free',
    RatioPerfect:'Perfect',
    RatioSquare:'Square',
    AboutTextBox:"About Slide",
    LongerDescriptionTextBox:"Longer Description",
    // Events
    KeyupEvent:"keyup",
    FocusEvent:"focusout",
    // Longer Description Presenter information
    SCPrsenterInformation:"Longer description shown on your audience's phones and if you hover the question while presenting.",
    MCPrsenterInformation:"Longer description shown on your audience's phones.",
    OEPrsenterInformation:"Appears in the presentation prior to showing the answers and in participants devices.",

    presentScreenRouterName:'present',

    hideandShowResponse:'HideandShowResponse'

}
